Repository Gagandeep-2003/driver-drowsiness-detection-system, pull requests merged in 2025-07, with the labels that each got.

#22 Fixed Issues in GUI and Responsiveness of GUI ( fixes issues #21, #18, #17)
  face-try.py
  main.py
Labels: enhancement, gssoc25, level3

#41 Redesigned and Expanded README with Full Project Overview, Setup, and Usage Details
  README.md
Labels: gssoc25, level1

#43 fix:39 Add error handling for missing alarm file with traceback logging
  blinkDetect.py
Labels: enhancement, gssoc25, level 2
