Repository Gagandeep-2003/driver-drowsiness-detection-system, pull requests merged in 2025-08, with the labels that each got.

#54 Docs: Improve Formatting of CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc25, level1

#48 Docs: Add Model Download Instructions to Fix RuntimeError
  CONTRIBUTING.md
  README.md
  blinkDetect.py
Labels: bug, documentation, gssoc25, level1

#51 Create Add License and Update README
  Add License and Update README
Labels: documentation, gssoc25, level1

#63 Made easy access of many variables For Module "#50 Dashboard"
  blinkDetect.py
Labels: enhancement, gssoc25, level3

#65 ✨ Feature: Dark/Light Mode Toggle Button for GUI
  main.py
Labels: enhancement, gssoc25, level 2

#64 Added The First Model Training Notebook
  models/ML_Models/ResNET+CNN (Tranfer Learning)/Drowsiness.ipynb
  models/ML_Models/ResNET+CNN (Tranfer Learning)/readme.md
  models/ML_Models/Using Transformers/readme.md
Labels: enhancement, gssoc25, level 2
